### ISSUE TITLE
Formulation class

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/hypy#11]
Initial implementation of HyPy _Formulation_ class.  

This is not a formal part of the HY Features spec, but is necessary (at least for the time being) for the HyPy project, and in particular for the current implementation of the _Catchment_ class.

**Comment by hellkite500** [comment]
I'm wondering if we should extend the base HY_Catchment into an NGEN catchment where we attach the formulation, this way we have the HY Features base true to the spec, and the application specific extension.  If we are going to keep the formulation packaged into the catchment at this level, I think we want to do that.  I've been working on how that formulation connects to a catchment in the calibration code, and this is starting to make the most sense to me.

**Comment by hellkite500** [comment]
Closed by #13
