### ISSUE TITLE
Implement Hydro Location

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/hypy#14]
To support linking observations to a nexus, this should be done via a `HydroLocation` association realizing the abstract nexus.
The relevant HY Features concept is represented [here](http://docs.opengeospatial.org/is/14-111r6/14-111r6.html#figure35).

The nexus itself should remain a conceptual, topological feature, and the connection to observation data is made via the hydro location.  This would invalidate the `Observation_Point` subclass of nexus, and migrate the functionality to a (most likely) sub type of hydro location.

**Comment by jdmattern-noaa** [comment]
I can make this change by making a Hydro_Location class subclass of Nexus. Are you saying to make nexus an abstract base class?

**Comment by hellkite500** [comment]
@jdmattern-noaa I'm working up this implementation now.
